package com.mustafa.trial.bags;

public enum BagKey {
	CUSTOMER_NAME,
	CUSTOMER_SURNAME,
	CUSTOMER_EMAIL,
	PHONE_NUMBER,
	CUSTOMER_ID,
	ADDRESS_ID,
	PHONE_ID,
	ACCOUNT_ID,
	ACCOUNT_NUMBER,
	ACCOUNT_AMOUNT,
	ADDRESS_ADDRESS
}
