package com.mustafa.trial.bags;

public interface BagKey {
	String CUSTOMER_NAME = "CUSTOMER_NAME";
	String CUSTOMER_SURNAME = "CUSTOMER_SURNAME";
	String CUSTOMER_EMAIL = "CUSTOMER_EMAIL";
	String PHONE_NUMBER ="PHONE_NUMBER";
	String CUSTOMER_ID = "CUSTOMER_ID";
	String ADDRESS_ID = "ADDRESS_ID";
	String PHONE_ID = "PHONE_ID";
	String ACCOUNT_ID = "ACCOUNT_ID";
	String ACCOUNT_NUMBER = "ACCOUNT_NUMBER";
	String ACCOUNT_AMOUNT = "CCOUNT_AMOUNT";
	String ADDRESS_ADDRESS = "ADDRESS_ADDRESS";
}
